/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Color;

/**
 *
 * @author estudiante307
 */
public class ExamplesJV extends javax.swing.JPanel {

    /**
     * Creates new form ExamplesJV
     */
    public ExamplesJV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnOrdTres = new javax.swing.JPanel();
        ordtresText = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Ejemplos Java");

        btnOrdTres.setBackground(new java.awt.Color(122, 0, 0));

        ordtresText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ordtresText.setForeground(new java.awt.Color(255, 255, 255));
        ordtresText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordtresText.setText("Ordenar 3 Numeros");
        ordtresText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordtresText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordtresTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordtresTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnOrdTresLayout = new javax.swing.GroupLayout(btnOrdTres);
        btnOrdTres.setLayout(btnOrdTresLayout);
        btnOrdTresLayout.setHorizontalGroup(
            btnOrdTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordtresText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnOrdTresLayout.setVerticalGroup(
            btnOrdTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordtresText, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(btnOrdTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordtresTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordtresTextMouseEntered
        // TODO add your handling code here:
        btnOrdTres.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_ordtresTextMouseEntered

    private void ordtresTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordtresTextMouseExited
        // TODO add your handling code here:
        btnOrdTres.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_ordtresTextMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnOrdTres;
    private javax.swing.JLabel ordtresText;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
