
package VISTA;

import MODELO.*;
import java.awt.event.KeyEvent;


public class Game1 extends javax.swing.JPanel {

    PanelSnake snake;
    
    public Game1() {
        initComponents();
        
        snake = new PanelSnake(350,20);
        this.add(snake);
        snake.setBounds(10, 10, 350, 350);
        snake.setOpaque(false);
        
        
        PanelFondo fondo = new PanelFondo(350,20);
        this.add(fondo);
        fondo.setBounds(10, 10, 350, 350);
        
        this.requestFocus(true);
    }
    
    private void startGame() {
    Arrastrarse moverSerpiente = new Arrastrarse(snake);
    Thread thread = new Thread(moverSerpiente);
    thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Up = new javax.swing.JLabel();
        Right = new javax.swing.JLabel();
        Down = new javax.swing.JLabel();
        Left = new javax.swing.JLabel();
        btnStart = new javax.swing.JPanel();
        startText = new javax.swing.JLabel();
        btnRestart = new javax.swing.JPanel();
        restartText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 232, 170));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-arriba.png"))); // NOI18N
        Up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpMouseClicked(evt);
            }
        });

        Right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-derecha.png"))); // NOI18N
        Right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RightMouseClicked(evt);
            }
        });

        Down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-abajo.png"))); // NOI18N
        Down.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DownMouseClicked(evt);
            }
        });

        Left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-izquierda.png"))); // NOI18N
        Left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeftMouseClicked(evt);
            }
        });

        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        startText.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        startText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startText.setText("JUGAR");

        javax.swing.GroupLayout btnStartLayout = new javax.swing.GroupLayout(btnStart);
        btnStart.setLayout(btnStartLayout);
        btnStartLayout.setHorizontalGroup(
            btnStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnStartLayout.setVerticalGroup(
            btnStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startText, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestartMouseClicked(evt);
            }
        });

        restartText.setFont(new java.awt.Font("Roboto Black", 2, 22)); // NOI18N
        restartText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restartText.setText("REINICIAR");

        javax.swing.GroupLayout btnRestartLayout = new javax.swing.GroupLayout(btnRestart);
        btnRestart.setLayout(btnRestartLayout);
        btnRestartLayout.setHorizontalGroup(
            btnRestartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restartText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRestartLayout.setVerticalGroup(
            btnRestartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restartText, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Up, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                snake.cambiarDireccion("Left");
                break;
            case KeyEvent.VK_RIGHT:
                snake.cambiarDireccion("Right");
                break;
            case KeyEvent.VK_UP:
                snake.cambiarDireccion("Up");
                break;
            case KeyEvent.VK_DOWN:
                snake.cambiarDireccion("Down");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpMouseClicked
        // TODO add your handling code here:
        snake.cambiarDireccion("Up");
    }//GEN-LAST:event_UpMouseClicked

    private void RightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightMouseClicked
        // TODO add your handling code here:
        snake.cambiarDireccion("Right");
    }//GEN-LAST:event_RightMouseClicked

    private void DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DownMouseClicked
        // TODO add your handling code here:
        snake.cambiarDireccion("Down");
    }//GEN-LAST:event_DownMouseClicked

    private void LeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeftMouseClicked
        // TODO add your handling code here:
        snake.cambiarDireccion("Left");
    }//GEN-LAST:event_LeftMouseClicked

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
        snake.iniciarJuego();
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnRestartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestartMouseClicked
        // TODO add your handling code here:
        snake.reiniciarJuego();
    }//GEN-LAST:event_btnRestartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Down;
    private javax.swing.JLabel Left;
    private javax.swing.JLabel Right;
    private javax.swing.JLabel Up;
    private javax.swing.JPanel btnRestart;
    private javax.swing.JPanel btnStart;
    private javax.swing.JLabel restartText;
    private javax.swing.JLabel startText;
    // End of variables declaration//GEN-END:variables
}
