/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author diego
 */
public class MainGUI2 extends javax.swing.JFrame {

    int xMouse, yMouse;
    public MainGUI2() {
        initComponents();
        
        UI cs = new UI();
        cs.setSize(540,410);
        cs.setLocation(0,0);
        
        content.removeAll();
        content.add(cs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menuNav = new javax.swing.JPanel();
        menuText = new javax.swing.JLabel();
        separatorText = new javax.swing.JLabel();
        btnEjem = new javax.swing.JPanel();
        ejemText = new javax.swing.JLabel();
        btnClass = new javax.swing.JPanel();
        classText = new javax.swing.JLabel();
        btnMios = new javax.swing.JPanel();
        miosText = new javax.swing.JLabel();
        btnGames = new javax.swing.JPanel();
        gamesText = new javax.swing.JLabel();
        btnSemi = new javax.swing.JPanel();
        semiText = new javax.swing.JLabel();
        btnAbout = new javax.swing.JPanel();
        aboutText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closeText = new javax.swing.JLabel();
        bannerT = new javax.swing.JPanel();
        titleB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuNav.setBackground(new java.awt.Color(122, 0, 0));
        menuNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuText.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setText("Menú");
        menuNav.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 37, -1, 44));

        separatorText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        separatorText.setForeground(new java.awt.Color(255, 255, 255));
        separatorText.setText("___________________________");
        menuNav.add(separatorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, -1, -1));

        btnEjem.setBackground(new java.awt.Color(122, 0, 0));
        btnEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjemMouseClicked(evt);
            }
        });
        btnEjem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ejemText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        ejemText.setForeground(new java.awt.Color(255, 255, 255));
        ejemText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ejemText.setText("Ejemplos Java");
        ejemText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ejemText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejemTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ejemTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ejemTextMouseExited(evt);
            }
        });
        btnEjem.add(ejemText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        menuNav.add(btnEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 50));

        btnClass.setBackground(new java.awt.Color(122, 0, 0));

        classText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        classText.setForeground(new java.awt.Color(255, 255, 255));
        classText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classText.setText("Programas en Clase");
        classText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                classTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                classTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnClassLayout = new javax.swing.GroupLayout(btnClass);
        btnClass.setLayout(btnClassLayout);
        btnClassLayout.setHorizontalGroup(
            btnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnClassLayout.setVerticalGroup(
            btnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuNav.add(btnClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 50));

        btnMios.setBackground(new java.awt.Color(122, 0, 0));

        miosText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        miosText.setForeground(new java.awt.Color(255, 255, 255));
        miosText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miosText.setText("Programas Propios");
        miosText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miosTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miosTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMiosLayout = new javax.swing.GroupLayout(btnMios);
        btnMios.setLayout(btnMiosLayout);
        btnMiosLayout.setHorizontalGroup(
            btnMiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miosText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnMiosLayout.setVerticalGroup(
            btnMiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miosText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuNav.add(btnMios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 260, 50));

        btnGames.setBackground(new java.awt.Color(122, 0, 0));

        gamesText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        gamesText.setForeground(new java.awt.Color(255, 255, 255));
        gamesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamesText.setText("Juegos");
        gamesText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gamesText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gamesTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gamesTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGamesLayout = new javax.swing.GroupLayout(btnGames);
        btnGames.setLayout(btnGamesLayout);
        btnGamesLayout.setHorizontalGroup(
            btnGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamesText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnGamesLayout.setVerticalGroup(
            btnGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamesText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuNav.add(btnGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 50));

        btnSemi.setBackground(new java.awt.Color(122, 0, 0));

        semiText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        semiText.setForeground(new java.awt.Color(255, 255, 255));
        semiText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semiText.setText("Seminario");
        semiText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semiText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semiTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                semiTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                semiTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSemiLayout = new javax.swing.GroupLayout(btnSemi);
        btnSemi.setLayout(btnSemiLayout);
        btnSemiLayout.setHorizontalGroup(
            btnSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semiText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnSemiLayout.setVerticalGroup(
            btnSemiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semiText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuNav.add(btnSemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 50));

        btnAbout.setBackground(new java.awt.Color(122, 0, 0));

        aboutText.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        aboutText.setForeground(new java.awt.Color(255, 255, 255));
        aboutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutText.setText("Acerca de");
        aboutText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAboutLayout = new javax.swing.GroupLayout(btnAbout);
        btnAbout.setLayout(btnAboutLayout);
        btnAboutLayout.setHorizontalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnAboutLayout.setVerticalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuNav.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 260, 50));

        bg.add(menuNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 500));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 540, 410));

        header.setBackground(new java.awt.Color(204, 204, 204));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setPreferredSize(new java.awt.Dimension(32, 32));

        closeText.setFont(new java.awt.Font("Roboto Thin", 1, 26)); // NOI18N
        closeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeText.setText("x");
        closeText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeText.setPreferredSize(new java.awt.Dimension(32, 32));
        closeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeLayout.createSequentialGroup()
                .addComponent(closeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 768, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        bannerT.setBackground(new java.awt.Color(204, 204, 204));
        bannerT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleB.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titleB.setText("PROYECTO: ALEJANDRO GUAPACHA");
        bannerT.add(titleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 11, -1, 76));

        bg.add(bannerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 540, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // Optener posicion del Mouse
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // Aqui es donde arrastraremos la ventana
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void closeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTextMouseClicked
        // Cerrar la ventana
        System.exit(0);
    }//GEN-LAST:event_closeTextMouseClicked

    private void closeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTextMouseEntered
        // Cambiar el color del boton 
        Color marronExit = new Color(122,0,0);
        close.setBackground(marronExit);
        closeText.setForeground(Color.WHITE);
    }//GEN-LAST:event_closeTextMouseEntered

    private void closeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeTextMouseExited
        // Tdevolver al color original
        Color grisHeader = new Color(204, 204, 204);
        close.setBackground(grisHeader);
        closeText.setForeground(Color.BLACK);
    }//GEN-LAST:event_closeTextMouseExited

    private void ejemTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemTextMouseEntered
        // cambiar el color del boton
        btnEjem.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_ejemTextMouseEntered

    private void ejemTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemTextMouseExited
        // Regresar el color del boton
        btnEjem.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_ejemTextMouseExited

    private void classTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classTextMouseEntered
        // Cambio color
        btnClass.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_classTextMouseEntered

    private void classTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classTextMouseExited
        // Regresar al oclor original
        btnClass.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_classTextMouseExited

    private void miosTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miosTextMouseEntered
        // Cambiar color
        btnMios.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_miosTextMouseEntered

    private void miosTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miosTextMouseExited
        // Devolver Color
        btnMios.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_miosTextMouseExited

    private void gamesTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesTextMouseEntered
        // Cambiar el color
        btnGames.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_gamesTextMouseEntered

    private void gamesTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesTextMouseExited
        // Regresar al color
        btnGames.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_gamesTextMouseExited

    private void classTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classTextMouseClicked
        // TODO add your handling code here:
        ProgClass cs = new ProgClass();
        cs.setSize(540,410);
        cs.setLocation(0,0);
        
        content.removeAll();
        content.add(cs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_classTextMouseClicked

    private void semiTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semiTextMouseEntered
        // Cambio de color del boton
        btnSemi.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_semiTextMouseEntered

    private void semiTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semiTextMouseExited
        // Regresar el color original
        btnSemi.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_semiTextMouseExited

    private void aboutTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTextMouseEntered
        // cambiar color
        btnAbout.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_aboutTextMouseEntered

    private void aboutTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTextMouseExited
        // Regresar color original
        btnAbout.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_aboutTextMouseExited

    private void aboutTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTextMouseClicked
        // Abrir la otra ventana
        About ab = new About();
        ab.setSize(540,410);
        ab.setLocation(0,0);
        
        content.removeAll();
        content.add(ab, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_aboutTextMouseClicked

    private void btnEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEjemMouseClicked

    private void ejemTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemTextMouseClicked
        // TODO add your handling code here:
        ExamplesJV jv = new ExamplesJV();
        jv.setSize(540,410);
        jv.setLocation(0,0);
        
        content.removeAll();
        content.add(jv, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_ejemTextMouseClicked

    private void semiTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semiTextMouseClicked
        // La ventana de seminario
        SeminarioGUI sm = new SeminarioGUI();
        sm.setSize(540,410);
        sm.setLocation(0,0);
        
        content.removeAll();
        content.add(sm, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_semiTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutText;
    private javax.swing.JPanel bannerT;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnAbout;
    private javax.swing.JPanel btnClass;
    private javax.swing.JPanel btnEjem;
    private javax.swing.JPanel btnGames;
    private javax.swing.JPanel btnMios;
    private javax.swing.JPanel btnSemi;
    private javax.swing.JLabel classText;
    private javax.swing.JPanel close;
    private javax.swing.JLabel closeText;
    private javax.swing.JPanel content;
    private javax.swing.JLabel ejemText;
    private javax.swing.JLabel gamesText;
    private javax.swing.JPanel header;
    private javax.swing.JPanel menuNav;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel miosText;
    private javax.swing.JLabel semiText;
    private javax.swing.JLabel separatorText;
    private javax.swing.JLabel titleB;
    // End of variables declaration//GEN-END:variables
}
