/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

/**
 *
 * @author diego
 */
public class ProgClass extends javax.swing.JPanel {

    /**
     * Creates new form ProgClass
     */
    public ProgClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btnOrd1 = new javax.swing.JPanel();
        ord1Text = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ord1Text.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        ord1Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ord1Text.setText("Ordenar 3 Numeros");

        javax.swing.GroupLayout btnOrd1Layout = new javax.swing.GroupLayout(btnOrd1);
        btnOrd1.setLayout(btnOrd1Layout);
        btnOrd1Layout.setHorizontalGroup(
            btnOrd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ord1Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnOrd1Layout.setVerticalGroup(
            btnOrd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ord1Text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnOrd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnOrd1;
    private javax.swing.JLabel ord1Text;
    // End of variables declaration//GEN-END:variables
}
