/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

/**
 *
 * @author estudiante307
 */
public class SeminarioGUI extends javax.swing.JPanel {

    /**
     * Creates new form SeminarioGUI
     */
    String dir;
    String nombre;
    char cual;
    public SeminarioGUI() {
        initComponents();
        cual='A';
        dir="/VISTA/Imagenes/";
        
        nombre=cual+"1.jpg";
        cargarImagen(dir, nombre);
    }
    
    public void cargarImagen(String dir, String nombre){
        imSm.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir + nombre)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLeft = new javax.swing.JPanel();
        left = new javax.swing.JLabel();
        btnRight = new javax.swing.JPanel();
        right = new javax.swing.JLabel();
        bgIm = new javax.swing.JPanel();
        imSm = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seminario");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-correcta.png"))); // NOI18N

        javax.swing.GroupLayout btnLeftLayout = new javax.swing.GroupLayout(btnLeft);
        btnLeft.setLayout(btnLeftLayout);
        btnLeftLayout.setHorizontalGroup(
            btnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLeftLayout.setVerticalGroup(
            btnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 359, -1, -1));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flc left.png"))); // NOI18N

        javax.swing.GroupLayout btnRightLayout = new javax.swing.GroupLayout(btnRight);
        btnRight.setLayout(btnRightLayout);
        btnRightLayout.setHorizontalGroup(
            btnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRightLayout.setVerticalGroup(
            btnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, 40, 40));

        javax.swing.GroupLayout bgImLayout = new javax.swing.GroupLayout(bgIm);
        bgIm.setLayout(bgImLayout);
        bgImLayout.setHorizontalGroup(
            bgImLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imSm, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        bgImLayout.setVerticalGroup(
            bgImLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imSm, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        bg.add(bgIm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 440, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgIm;
    private javax.swing.JPanel btnLeft;
    private javax.swing.JPanel btnRight;
    private javax.swing.JLabel imSm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel left;
    private javax.swing.JLabel right;
    // End of variables declaration//GEN-END:variables
}
