/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Color;
import static jdk.nashorn.internal.objects.NativeString.substring;

/**
 *
 * @author estudiante307
 */
public class SeminarioGUI extends javax.swing.JPanel {

    /**
     * Creates new form SeminarioGUI
     */
    String dir;
    String nombre;
    char cual;
    public SeminarioGUI() {
        initComponents();
        cual='A';
        dir="/VISTA/Images/";
        
        nombre=cual+"1.jpg";
        cargarImagen(dir, nombre);
    }
    
    public void cargarImagen(String dir, String nombre){
        imSm.setIcon(new javax.swing.ImageIcon(getClass().getResource(dir + nombre)));
    }
    
    public void definirNextNombre(){
        String snumero=nombre.substring(1,2);
        int numero = Integer.parseInt(snumero);
        
        numero++;
        
        if(numero>9)
            numero=1;
        nombre = cual + "" +numero+".jpg";
        
        cargarImagen(dir, nombre);
    }
    
    public void definirAntNombre(){
        String snumero=nombre.substring(1, 2);
        int numero= Integer.parseInt(snumero);
        
        numero --;
        
        if(numero<=0)
            numero=9;
        nombre = cual + "" +numero+".jpg";
        
        cargarImagen(dir, nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLeft = new javax.swing.JPanel();
        left = new javax.swing.JLabel();
        btnRight = new javax.swing.JPanel();
        right = new javax.swing.JLabel();
        bgIm = new javax.swing.JPanel();
        imSm = new javax.swing.JLabel();
        btnA = new javax.swing.JPanel();
        aText = new javax.swing.JLabel();
        btnB = new javax.swing.JPanel();
        bText = new javax.swing.JLabel();
        btnC = new javax.swing.JPanel();
        cText = new javax.swing.JLabel();
        btnD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seminario");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        left.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flecha-correcta.png"))); // NOI18N
        left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLeftLayout = new javax.swing.GroupLayout(btnLeft);
        btnLeft.setLayout(btnLeftLayout);
        btnLeftLayout.setHorizontalGroup(
            btnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLeftLayout.setVerticalGroup(
            btnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 359, -1, -1));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/flc left.png"))); // NOI18N
        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRightLayout = new javax.swing.GroupLayout(btnRight);
        btnRight.setLayout(btnRightLayout);
        btnRightLayout.setHorizontalGroup(
            btnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRightLayout.setVerticalGroup(
            btnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, 40, 40));

        bgIm.setBackground(new java.awt.Color(0, 0, 0));

        imSm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bgImLayout = new javax.swing.GroupLayout(bgIm);
        bgIm.setLayout(bgImLayout);
        bgImLayout.setHorizontalGroup(
            bgImLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imSm, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        bgImLayout.setVerticalGroup(
            bgImLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imSm, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        bg.add(bgIm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 440, 290));

        btnA.setBackground(new java.awt.Color(122, 0, 0));

        aText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        aText.setForeground(new java.awt.Color(255, 255, 255));
        aText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aText.setText("A");
        aText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnALayout = new javax.swing.GroupLayout(btnA);
        btnA.setLayout(btnALayout);
        btnALayout.setHorizontalGroup(
            btnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnALayout.setVerticalGroup(
            btnALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, 30));

        btnB.setBackground(new java.awt.Color(122, 0, 0));

        bText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bText.setForeground(new java.awt.Color(255, 255, 255));
        bText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bText.setText("B");
        bText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBLayout = new javax.swing.GroupLayout(btnB);
        btnB.setLayout(btnBLayout);
        btnBLayout.setHorizontalGroup(
            btnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBLayout.setVerticalGroup(
            btnBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 40, 30));

        btnC.setBackground(new java.awt.Color(122, 0, 0));
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCMouseExited(evt);
            }
        });

        cText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cText.setForeground(new java.awt.Color(255, 255, 255));
        cText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cText.setText("C");

        javax.swing.GroupLayout btnCLayout = new javax.swing.GroupLayout(btnC);
        btnC.setLayout(btnCLayout);
        btnCLayout.setHorizontalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnCLayout.setVerticalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 30));

        btnD.setBackground(new java.awt.Color(122, 0, 0));
        btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("D");

        javax.swing.GroupLayout btnDLayout = new javax.swing.GroupLayout(btnD);
        btnD.setLayout(btnDLayout);
        btnDLayout.setHorizontalGroup(
            btnDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnDLayout.setVerticalGroup(
            btnDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void leftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseClicked
        // TODO add your handling code here:
        definirNextNombre();
    }//GEN-LAST:event_leftMouseClicked

    private void rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightMouseClicked
        // TODO add your handling code here:
        definirAntNombre();
    }//GEN-LAST:event_rightMouseClicked

    private void bTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseEntered
        // TODO add your handling code here:
        btnB.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_bTextMouseEntered

    private void bTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseExited
        // TODO add your handling code here:
        btnB.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_bTextMouseExited

    private void aTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aTextMouseEntered
        // TODO add your handling code here:
        btnA.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_aTextMouseEntered

    private void aTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aTextMouseExited
        // TODO add your handling code here:
        btnA.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_aTextMouseExited

    private void bTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTextMouseClicked
        // Cambiamos al problema B
        cual='B';
        nombre=cual + "1.jpg";
        cargarImagen(dir,nombre);
    }//GEN-LAST:event_bTextMouseClicked

    private void aTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aTextMouseClicked
        // cambiamos al problma A
        cual='A';
        nombre=cual + "1.jpg";
        cargarImagen(dir,nombre);
    }//GEN-LAST:event_aTextMouseClicked

    private void btnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseEntered
        // TODO add your handling code here:
        btnC.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_btnCMouseEntered

    private void btnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseExited
        // TODO add your handling code here:
        btnC.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_btnCMouseExited

    private void btnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseClicked
        // TODO add your handling code here:
        cual='C';
        nombre=cual + "1.jpg";
        cargarImagen(dir,nombre);
    }//GEN-LAST:event_btnCMouseClicked

    private void btnDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMouseEntered
        // TODO add your handling code here:
        btnD.setBackground(new Color(160,0,0));
    }//GEN-LAST:event_btnDMouseEntered

    private void btnDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMouseExited
        // TODO add your handling code here:
        btnD.setBackground(new Color(122,0,0));
    }//GEN-LAST:event_btnDMouseExited

    private void btnDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMouseClicked
        // TODO add your handling code here:
        cual='D';
        nombre=cual + "1.jpg";
        cargarImagen(dir,nombre);
    }//GEN-LAST:event_btnDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aText;
    private javax.swing.JLabel bText;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgIm;
    private javax.swing.JPanel btnA;
    private javax.swing.JPanel btnB;
    private javax.swing.JPanel btnC;
    private javax.swing.JPanel btnD;
    private javax.swing.JPanel btnLeft;
    private javax.swing.JPanel btnRight;
    private javax.swing.JLabel cText;
    private javax.swing.JLabel imSm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel left;
    private javax.swing.JLabel right;
    // End of variables declaration//GEN-END:variables
}
