/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.CalcIntereses;
import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author diego
 */
public class SimuladorCred extends javax.swing.JPanel {

    /**
     * Creates new form SimuladorCred
     */
    public SimuladorCred() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        areaMonto = new MODELO.TextFieldSuggestion();
        textMonto = new javax.swing.JLabel();
        textTasa = new javax.swing.JLabel();
        areaInteres = new MODELO.TextFieldSuggestion();
        porcentaje = new javax.swing.JLabel();
        textCuotas = new javax.swing.JLabel();
        areaCuotas = new MODELO.TextFieldSuggestion();
        separador1 = new javax.swing.JLabel();
        texTotalMonto = new javax.swing.JLabel();
        textValorCuota = new javax.swing.JLabel();
        mostrarCuota = new MODELO.TextFieldSuggestion();
        mostrarTotal = new MODELO.TextFieldSuggestion();
        btnSmlr = new javax.swing.JPanel();
        smlrText = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(72, 61, 139));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Simulador de Credito Bancario");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, 47));

        texto1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setText("Aqui podrá saber el valor de cada una de las cuotas que tendrá que pagar mes a mes, además");
        bg.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 480, 20));

        texto2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setText("de saber cuanto será el monto del total que usted habrá pagado al final.");
        bg.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 470, -1));

        areaMonto.setForeground(new java.awt.Color(255, 255, 255));
        areaMonto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bg.add(areaMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 170, -1));

        textMonto.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        textMonto.setForeground(new java.awt.Color(255, 255, 255));
        textMonto.setText("Ingrese el valor del préstamo:");
        bg.add(textMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 30));

        textTasa.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        textTasa.setForeground(new java.awt.Color(255, 255, 255));
        textTasa.setText("Ingrese la tasa de interés anual:");
        bg.add(textTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 30));

        areaInteres.setForeground(new java.awt.Color(255, 255, 255));
        areaInteres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bg.add(areaInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, -1));

        porcentaje.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        porcentaje.setText("%");
        bg.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 30, 30));

        textCuotas.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        textCuotas.setForeground(new java.awt.Color(255, 255, 255));
        textCuotas.setText("Ingrese el número de cuotas:");
        bg.add(textCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 190, 40));

        areaCuotas.setForeground(new java.awt.Color(255, 255, 255));
        areaCuotas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bg.add(areaCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, -1));

        separador1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separador1.setForeground(new java.awt.Color(255, 255, 255));
        separador1.setText("______________________________________________________________________");
        bg.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 500, 40));

        texTotalMonto.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        texTotalMonto.setForeground(new java.awt.Color(255, 255, 255));
        texTotalMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texTotalMonto.setText("Monto Total a Pagar");
        bg.add(texTotalMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 180, 30));

        textValorCuota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        textValorCuota.setForeground(new java.awt.Color(255, 255, 255));
        textValorCuota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textValorCuota.setText("Cuota mensual");
        bg.add(textValorCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 140, 30));

        mostrarCuota.setEditable(false);
        mostrarCuota.setForeground(new java.awt.Color(255, 255, 255));
        mostrarCuota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostrarCuota.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mostrarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCuotaActionPerformed(evt);
            }
        });
        bg.add(mostrarCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 150, -1));

        mostrarTotal.setEditable(false);
        mostrarTotal.setForeground(new java.awt.Color(255, 255, 255));
        mostrarTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostrarTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bg.add(mostrarTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, -1));

        btnSmlr.setBackground(new java.awt.Color(72, 61, 139));
        btnSmlr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        smlrText.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        smlrText.setForeground(new java.awt.Color(255, 255, 255));
        smlrText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smlrText.setText("SIMULAR");
        smlrText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        smlrText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smlrTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smlrTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                smlrTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSmlrLayout = new javax.swing.GroupLayout(btnSmlr);
        btnSmlr.setLayout(btnSmlrLayout);
        btnSmlrLayout.setHorizontalGroup(
            btnSmlrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlrText, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnSmlrLayout.setVerticalGroup(
            btnSmlrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smlrText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(btnSmlr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarCuotaActionPerformed

    private void smlrTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smlrTextMouseEntered
        // TODO add your handling code here:
        btnSmlr.setBackground(new Color(72,109,164));
    }//GEN-LAST:event_smlrTextMouseEntered

    private void smlrTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smlrTextMouseExited
        // TODO add your handling code here:
        btnSmlr.setBackground(new Color(72,61,139));
    }//GEN-LAST:event_smlrTextMouseExited

    private void smlrTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smlrTextMouseClicked
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#,###.##"); // Esto formatea a 2 decimales
        
        String mon = areaMonto.getText();
        double x = Double.parseDouble(mon);
        String tasa= areaInteres.getText();
        double y = Double.parseDouble(tasa);
        String cuo= areaCuotas.getText();
        int z = Integer.parseInt(cuo);
        
        CalcIntereses bank= new CalcIntereses(x,y,z);
        double cuotaMensual = bank.calcularCuotaMensual();
        String cuotaFormateada = df.format(cuotaMensual);
        mostrarCuota.setText(cuotaFormateada);
        
        double totalPago = bank.calcularMontoTotal();
        String totalFormateado = df.format(totalPago);
        mostrarTotal.setText(totalFormateado);
    }//GEN-LAST:event_smlrTextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MODELO.TextFieldSuggestion areaCuotas;
    private MODELO.TextFieldSuggestion areaInteres;
    private MODELO.TextFieldSuggestion areaMonto;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnSmlr;
    private MODELO.TextFieldSuggestion mostrarCuota;
    private MODELO.TextFieldSuggestion mostrarTotal;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel smlrText;
    private javax.swing.JLabel texTotalMonto;
    private javax.swing.JLabel textCuotas;
    private javax.swing.JLabel textMonto;
    private javax.swing.JLabel textTasa;
    private javax.swing.JLabel textValorCuota;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
